# -*- coding: utf-8 -*-
"""BAR.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Hw_loJPwq_FEdPYoEZFCU5zK5zE9wM7b
"""

import pandas as pd

############nov df LOS ###################!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

gsheetid = "15HJ7wxyUmo-gcl5_y1M9gl4Ti-JSsYEJZCjoI76s-Xk"
sheet_name = "ApartmajiAdria"

gsheet_url = "https://docs.google.com/spreadsheets/d/{}/gviz/tq?tqx=out:csv&sheet={}".format(gsheetid, sheet_name)

gsheet_url

df = pd.read_csv(gsheet_url)

#string BAR, ki se doda k številki v celici

df['BAR'] = df['BAR'].apply(lambda x: f"BAR{x}")

#####################################

#Številka hotela, ki se doda v vrstico

import numpy as np
df['ApartmajiAdria'] = 1001011
df.head()

####################################

#Številka, ki jo zahteva PHOBS

import numpy as np
df['nicla'] = 0
df.head()

######################

#iz PHOBSA , YIELD

import numpy as np
df['LOS'] = 16283
df.head()

########################

df['LOS'] = df['LOS'].apply(lambda x: f"YIELD{x}")

#vrstni red tabelice- heading
vrstice_imena1noc = ['ApartmajiAdria','Datum','nicla','BAR','LOS']
df = df.reindex(columns=vrstice_imena1noc)

df.columns = ['ApartmajiAdria','Datum','nicla','BAR','Yield']

#print(df.to_string(index=False, header=True))


#df.to_csv (r'C:\Users\Uporabnik\Desktop\PHOBS\NEW\GHB.csv', index = False, header=False)



import pandas as pd

############nov df LOS ###################!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

gsheetid = "15HJ7wxyUmo-gcl5_y1M9gl4Ti-JSsYEJZCjoI76s-Xk"
sheet_name = "StandardMobileHomes"

gsheet_url = "https://docs.google.com/spreadsheets/d/{}/gviz/tq?tqx=out:csv&sheet={}".format(gsheetid, sheet_name)

gsheet_url

df1 = pd.read_csv(gsheet_url)

#string BAR, ki se doda k številki v celici

df1['BAR'] = df1['BAR'].apply(lambda x: f"BAR{x}")

#####################################

#Številka hotela, ki se doda v vrstico

import numpy as np
df1['StandardMobileHomes'] = 1001012
df1.head()

####################################

#Številka, ki jo zahteva PHOBS

import numpy as np
df1['nicla'] = 0
df1.head()

######################

#iz PHOBSA , YIELD

import numpy as np
df1['LOS'] = 16552
df1.head()

########################

df1['LOS'] = df1['LOS'].apply(lambda x: f"YIELD{x}")

#vrstni red tabelice- heading
vrstice_imena1noc = ['StandardMobileHomes','Datum','nicla','BAR','LOS']
df1 = df1.reindex(columns=vrstice_imena1noc)

df1.columns = ['StandardMobileHomes','Datum','nicla','BAR','Yield']

print(df1.to_string(index=False, header=True))

#df.to_csv (r'C:\Users\Uporabnik\Desktop\PHOBS\NEW\GHB.csv', index = False, header=False)



import pandas as pd

############nov df LOS ###################!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

gsheetid = "15HJ7wxyUmo-gcl5_y1M9gl4Ti-JSsYEJZCjoI76s-Xk"
sheet_name = "PremiumMobileHomes"

gsheet_url = "https://docs.google.com/spreadsheets/d/{}/gviz/tq?tqx=out:csv&sheet={}".format(gsheetid, sheet_name)

gsheet_url

df2 = pd.read_csv(gsheet_url)

#string BAR, ki se doda k številki v celici

df2['BAR'] = df2['BAR'].apply(lambda x: f"BAR{x}")

#####################################

#Številka hotela, ki se doda v vrstico

import numpy as np
df2['PremiumMobileHomes'] = 1001011
df2.head()

####################################

#Številka, ki jo zahteva PHOBS

import numpy as np
df2['nicla'] = 0
df2.head()

######################

#iz PHOBSA , YIELD

import numpy as np
df2['LOS'] = 16242
df2.head()

########################

df2['LOS'] = df2['LOS'].apply(lambda x: f"YIELD{x}")

#vrstni red tabelice- heading
vrstice_imena1noc = ['PremiumMobileHomes','Datum','nicla','BAR','LOS']
df2 = df2.reindex(columns=vrstice_imena1noc)

df2.columns = ['PremiumMobileHomes','Datum','nicla','BAR','Yield']

#print(df2.to_string(index=False, header=True))

#df.to_csv (r'C:\Users\Uporabnik\Desktop\PHOBS\NEW\GHB.csv', index = False, header=False)



import pandas as pd

############nov df LOS ###################!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

gsheetid = "15HJ7wxyUmo-gcl5_y1M9gl4Ti-JSsYEJZCjoI76s-Xk"
sheet_name = "HotelConvent"

gsheet_url = "https://docs.google.com/spreadsheets/d/{}/gviz/tq?tqx=out:csv&sheet={}".format(gsheetid, sheet_name)

gsheet_url

df3 = pd.read_csv(gsheet_url)

#string BAR, ki se doda k številki v celici

df3['BAR'] = df3['BAR'].apply(lambda x: f"BAR{x}")

#####################################

#Številka hotela, ki se doda v vrstico

import numpy as np
df3['HotelConvent'] = 1001011
df3.head()

####################################

#Številka, ki jo zahteva PHOBS

import numpy as np
df3['nicla'] = 0
df3.head()

######################

#iz PHOBSA , YIELD

import numpy as np
df3['LOS'] = 16355
df3.head()

########################

df3['LOS'] = df3['LOS'].apply(lambda x: f"YIELD{x}")

#vrstni red tabelice- heading
vrstice_imena1noc = ['HotelConvent','Datum','nicla','BAR','LOS']
df3 = df3.reindex(columns=vrstice_imena1noc)

df3.columns = ['HotelConvent','Datum','nicla','BAR','Yield']

#print(df3.to_string(index=False, header=True))

#df.to_csv (r'C:\Users\Uporabnik\Desktop\PHOBS\NEW\GHB.csv', index = False, header=False)



import pandas as pd

############nov df LOS ###################!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

gsheetid = "15HJ7wxyUmo-gcl5_y1M9gl4Ti-JSsYEJZCjoI76s-Xk"
sheet_name = "OliveSuites"

gsheet_url = "https://docs.google.com/spreadsheets/d/{}/gviz/tq?tqx=out:csv&sheet={}".format(gsheetid, sheet_name)

gsheet_url

df4 = pd.read_csv(gsheet_url)

#string BAR, ki se doda k številki v celici

df4['BAR'] = df4['BAR'].apply(lambda x: f"BAR{x}")

#####################################

#Številka hotela, ki se doda v vrstico

import numpy as np
df4['OliveSuites'] = 1001011
df4.head()

####################################

#Številka, ki jo zahteva PHOBS

import numpy as np
df4['nicla'] = 0
df4.head()

######################

#iz PHOBSA , YIELD

import numpy as np
df4['LOS'] = 16244
df4.head()

########################

df4['LOS'] = df4['LOS'].apply(lambda x: f"YIELD{x}")

#vrstni red tabelice- heading
vrstice_imena1noc = ['OliveSuites','Datum','nicla','BAR','LOS']
df4 = df4.reindex(columns=vrstice_imena1noc)

df4.columns = ['OliveSuites','Datum','nicla','BAR','Yield']

#print(df4.to_string(index=False, header=True))

#df.to_csv (r'C:\Users\Uporabnik\Desktop\PHOBS\NEW\GHB.csv', index = False, header=False)



import pandas as pd

############nov df LOS ###################!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

gsheetid = "15HJ7wxyUmo-gcl5_y1M9gl4Ti-JSsYEJZCjoI76s-Xk"
sheet_name = "Vilebrezbalkona"

gsheet_url = "https://docs.google.com/spreadsheets/d/{}/gviz/tq?tqx=out:csv&sheet={}".format(gsheetid, sheet_name)

gsheet_url

df5 = pd.read_csv(gsheet_url)

#string BAR, ki se doda k številki v celici

df5['BAR'] = df5['BAR'].apply(lambda x: f"BAR{x}")

#####################################

#Številka hotela, ki se doda v vrstico

import numpy as np
df5['Vilebrezbalkona'] = 1001011
df5.head()

####################################

#Številka, ki jo zahteva PHOBS

import numpy as np
df5['nicla'] = 0
df5.head()

######################

#iz PHOBSA , YIELD

import numpy as np
df5['LOS'] = 16284
df5.head()

########################

df5['LOS'] = df5['LOS'].apply(lambda x: f"YIELD{x}")

#vrstni red tabelice- heading
vrstice_imena1noc = ['Vilebrezbalkona','Datum','nicla','BAR','LOS']
df5 = df5.reindex(columns=vrstice_imena1noc)

df5.columns = ['Vilebrezbalkona','Datum','nicla','BAR','Yield']

#print(df5.to_string(index=False, header=True))

#df.to_csv (r'C:\Users\Uporabnik\Desktop\PHOBS\NEW\GHB.csv', index = False, header=False)



import pandas as pd

############nov df LOS ###################!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

gsheetid = "15HJ7wxyUmo-gcl5_y1M9gl4Ti-JSsYEJZCjoI76s-Xk"
sheet_name = "Vilezbalkonom"

gsheet_url = "https://docs.google.com/spreadsheets/d/{}/gviz/tq?tqx=out:csv&sheet={}".format(gsheetid, sheet_name)

gsheet_url

df6 = pd.read_csv(gsheet_url)

#string BAR, ki se doda k številki v celici

df6['BAR'] = df5['BAR'].apply(lambda x: f"BAR{x}")

#####################################

#Številka hotela, ki se doda v vrstico

import numpy as np
df6['Vilezbalkonom'] = 1001011
df6.head()

####################################

#Številka, ki jo zahteva PHOBS

import numpy as np
df6['nicla'] = 0
df6.head()

######################

#iz PHOBSA , YIELD

import numpy as np
df6['LOS'] = 15985
df6.head()

########################

df6['LOS'] = df6['LOS'].apply(lambda x: f"YIELD{x}")

#vrstni red tabelice- heading
vrstice_imena1noc = ['Vilezbalkonom','Datum','nicla','BAR','LOS']
df6 = df6.reindex(columns=vrstice_imena1noc)

df6.columns = ['Vilezbalkonom','Datum','nicla','BAR','Yield']

#print(df6.to_string(index=False, header=True))

#df.to_csv (r'C:\Users\Uporabnik\Desktop\PHOBS\NEW\GHB.csv', index = False, header=False)

"""<div style="clear: both;">
<div>
      <h2><b>EXPORT</b>4PHOBS</h2>
     <img src="https://scontent.flju1-1.fna.fbcdn.net/v/t39.30808-1/538848259_1373858921407395_3734947029332493437_n.jpg?stp=c221.221.1034.1034a_dst-jpg_s480x480_tt6&_nc_cat=110&ccb=1-7&_nc_sid=2d3e12&_nc_ohc=nLyDiOB5EM8Q7kNvwEw-9Xf&_nc_oc=Adm0RsJmASURcGiXVvWUyJRIrypsmZsQEM5WYIv2uG8ZFEp5f1wteeqopUsLj6bPgFk&_nc_zt=24&_nc_ht=scontent.flju1-1.fna&_nc_gid=J2ABA-OjzFAu8lGZyNEJ3g&oh=00_AffBA_KZ8YxYLhFZ2GHdTmTHnUp2bG6tZWV73qMxnj66Qg&oe=68FAB123" width="180" alt="">
  </div>
  </div>
  <div>
    <p>Generator za BAR cenike</p>
  </div>
</div>

<b>[ODPRI UREJEVALNIK BAR](https://docs.google.com/spreadsheets/d/15HJ7wxyUmo-gcl5_y1M9gl4Ti-JSsYEJZCjoI76s-Xk/edit?gid=1385640257#gid=1385640257)</b>

<br>
<button class="alert alert-block alert-success"onClick="window.location.href=window.location.href"><b>Osveži podatke ko vneseš v UREJEVALNIK BAR<b><i></button>

<div class="alert alert-block alert-info">
"""

import ipywidgets as widgets
from google.colab import files

a1 = widgets.Button(description="Apartmaji Adria", layout=widgets.Layout(width="33%"))
a2 = widgets.Button(description="Standard Mobile Homes", layout=widgets.Layout(width="33%"))
a3 = widgets.Button(description="Premium Mobile Homes", layout=widgets.Layout(width="33%"))
a4 = widgets.Button(description="Hotel Convent", layout=widgets.Layout(width="33%"))
a5 = widgets.Button(description="Olive Suites", layout=widgets.Layout(width="33%"))
a6 = widgets.Button(description="Vile brez balkona", layout=widgets.Layout(width="33%"))
a7 = widgets.Button(description="Vile z balkonom", layout=widgets.Layout(width="33%"))


h1 = widgets.HBox(children=[a1,a2,a3])
h1

h2 = widgets.HBox(children=[a4,a5,a6])
h2

h3 = widgets.HBox(children=[a7])
h3

h4 = widgets.VBox(children=[h1,h2,h3])
h4

from IPython.display import display
output = widgets.Output()
display(h4, output)

def on_button_clicked(b):
    with output:
        print("CSV file za Apartmaji Adria je ustvarjen. ")
        df.to_csv ('Apartmaji-Adria-4-Phobs.csv', index=None, header=None)
        files.download('Apartmaji-Adria-4-Phobs.csv')
a1.on_click(on_button_clicked)

def on_button_clicked(b):
    with output:
        print("CSV file za Standard Mobile Homes je ustvarjen. ")
        df1.to_csv ('Standard-Mobile-Homes-4-Phobs.csv', index=None, header=None)
        files.download('Standard-Mobile-Homes-4-Phobs.csv')
a2.on_click(on_button_clicked)

def on_button_clicked(b):
    with output:
        print("CSV file za Premium Mobile Homes je ustvarjen. ")
        df2.to_csv ('Premium-Mobile-Homes-4-Phobs.csv', index=None, header=None)
        files.download('Premium-Mobile-Homes-4-Phobs.csv')
a3.on_click(on_button_clicked)

def on_button_clicked(b):
    with output:
        print("CSV file za Hotel Convent je ustvarjen. ")
        df3.to_csv ('Hotel-Convent-4-Phobs.csv', index=None, header=None)
        files.download('Hotel-Convent-4-Phobs.csv')
a4.on_click(on_button_clicked)

def on_button_clicked(b):
    with output:
        print("CSV file za Olive Suites je ustvarjen. ")
        df4.to_csv ('Olive Suites-4-Phobs.csv', index=None, header=None)
        files.download('Olive Suites-4-Phobs.csv')
a5.on_click(on_button_clicked)

def on_button_clicked(b):
    with output:
        print("CSV file za Vile brez balkona je ustvarjen. ")
        df5.to_csv ('Vile-brez-balkona-4-Phobs.csv', index=None, header=None)
        files.download('Vile-brez-balkona-4-Phobs.csv')
a6.on_click(on_button_clicked)



def on_button_clicked(b):
    with output:
        print("CSV file za Vile z balkonom je ustvarjen. ")
        df6.to_csv ('Vile-z-balkonom-4-Phobs.csv', index=None, header=None)
        files.download('Vile-z-balkonom-4-Phobs.csv')
a7.on_click(on_button_clicked)

import ipywidgets as made
made.HTML(
    value="by M.Goja",
)